# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_key', models.CharField(max_length=40, unique=True)),
                ('api_key_encoded', models.CharField(blank=True, max_length=128)),
                ('hint', models.CharField(blank=True, help_text='* do not accurately reflect length of password', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
