# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20161025_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='random_key',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=128, unique=True),
        ),
    ]
