# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20161025_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='hint',
            field=models.CharField(blank=True, help_text="*'s do not accurately reflect length of password", max_length=16),
        ),
    ]
