# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 02:15
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20161025_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='api_key_encoded',
            field=models.CharField(blank=True, default=authentication.models.unusable_string, max_length=128),
        ),
        migrations.AlterField(
            model_name='token',
            name='random_key',
            field=models.CharField(default=authentication.models.unusable_string, max_length=128, unique=True),
        ),
    ]
