# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 02:27
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20161025_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='api_key_encoded',
            field=models.CharField(default=authentication.models.unusable_string, max_length=128),
        ),
        migrations.AlterField(
            model_name='token',
            name='hint',
            field=models.CharField(default='Not yet generated.', help_text="*'s do not accurately reflect length of password", max_length=18),
        ),
    ]
